"""empty message

Revision ID: 0c5dce3ebba4
Revises: 18bda347a18a
Create Date: 2018-12-19 21:18:46.739121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5dce3ebba4'
down_revision = '18bda347a18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('l1_cache', sa.Integer(), nullable=False),
    sa.Column('l2_cache', sa.Integer(), nullable=False),
    sa.Column('l3_cache', sa.Integer(), nullable=False),
    sa.Column('component_meta_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_meta_info_id'], ['componentmetainfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('component_meta_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_meta_info_id'], ['componentmetainfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('computer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=10), nullable=False),
    sa.Column('trunk_id', sa.Integer(), nullable=True),
    sa.Column('motherboard_id', sa.Integer(), nullable=True),
    sa.Column('ram_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motherboard_id'], ['motherboard.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ram_id'], ['ram.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trunk_id'], ['trunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('motherboard', sa.Column('pci_slots', sa.Integer(), nullable=False))
    op.add_column('motherboard', sa.Column('ram_slots', sa.Integer(), nullable=False))
    op.add_column('motherboard', sa.Column('used_pci_slots', sa.Integer(), nullable=False))
    op.add_column('motherboard', sa.Column('used_ram_slots', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motherboard', 'used_ram_slots')
    op.drop_column('motherboard', 'used_pci_slots')
    op.drop_column('motherboard', 'ram_slots')
    op.drop_column('motherboard', 'pci_slots')
    op.drop_table('computer')
    op.drop_table('ram')
    op.drop_table('processor')
    # ### end Alembic commands ###
