"""empty message

Revision ID: 18bda347a18a
Revises: 0f8b510da6f5
Create Date: 2018-12-17 00:17:08.861487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bda347a18a'
down_revision = '0f8b510da6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('componentmetainfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=10), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('warranty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warranty_id'], ['warranty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motherboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_factor', sa.String(length=10), nullable=False),
    sa.Column('chipset', sa.String(length=10), nullable=False),
    sa.Column('component_meta_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_meta_info_id'], ['componentmetainfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Numeric(precision=8), nullable=False),
    sa.Column('height', sa.Numeric(precision=8), nullable=False),
    sa.Column('form_factor', sa.String(length=10), nullable=False),
    sa.Column('component_meta_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_meta_info_id'], ['componentmetainfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trunk')
    op.drop_table('motherboard')
    op.drop_table('componentmetainfo')
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
