"""empty message

Revision ID: 289edc3b308a
Revises: 18bda347a18a
Create Date: 2018-12-19 21:39:50.544943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '289edc3b308a'
down_revision = '18bda347a18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('l1_cache', sa.Integer(), nullable=False),
    sa.Column('l2_cache', sa.Integer(), nullable=False),
    sa.Column('l3_cache', sa.Integer(), nullable=False),
    sa.Column('component_meta_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_meta_info_id'], ['componentmetainfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('component_meta_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_meta_info_id'], ['componentmetainfo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('computer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=10), nullable=False),
    sa.Column('trunk_id', sa.Integer(), nullable=True),
    sa.Column('motherboard_id', sa.Integer(), nullable=True),
    sa.Column('ram_id', sa.Integer(), nullable=True),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motherboard_id'], ['motherboard.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processor_id'], ['processor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ram_id'], ['ram.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trunk_id'], ['trunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    conn = op.get_bind().connection
    conn.executescript(
    """
    begin transaction;
        create temporary table motherboard_backup(
            id, form_factor, chipset, component_meta_info_id
        );
        insert into motherboard_backup
            select id, form_factor, chipset, component_meta_info_id from motherboard;
        drop table motherboard;
        create table motherboard (
            id integer not null primary key,
            form_factor text(10) not null,
            chipset text(10) not null,
            component_meta_info_id integer not null,
            pci_slots integer not null default 0,
            ram_slots integer not null default 0,
            used_pci_slots integer not null default 0,
            used_ram_slots integer not null default 0,
            foreign key(component_meta_info_id) references componentmetainfo(id)
        );
        insert into motherboard
            select id, form_factor, chipset, component_meta_info_id, 0, 0, 0, 0 from motherboard_backup;
        drop table motherboard_backup;
    commit;
    """
    )

def downgrade():
    conn = op.get_bind().connection
    conn.executescript(
    """
    begin transaction;
        create temporary table motherboard_backup(
            id, form_factor, chipset, component_meta_info_id
        );
        insert into motherboard_backup
            select id, form_factor, chipset, component_meta_info_id from motherboard;
        drop table motherboard;
        create table motherboard (
            id integer not null primary key,
            form_factor text(10) not null,
            chipset text(10) not null,
            component_meta_info_id integer not null,
            foreign key(component_meta_info_id) references componentmetainfo(id)
        );
        insert into motherboard
            select id, form_factor, chipset, component_meta_info_id from motherboard_backup;
        drop table motherboard_backup;
    commit;
    """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computer')
    op.drop_table('ram')
    op.drop_table('processor')
    # ### end Alembic commands ###
